<?php

namespace App\Http\Controllers\Admin\Func\Contract;

use App\Models\Admin\Func\Contract\RpaContractJys;
use Illuminate\Http\Request;

/**
 * 交易所管理
 * Class JysController
 * @package App\Http\Controllers\Admin\Func\Contract
 */
class JysController extends BaseController
{

    public $list = [
        'F1' => '郑州交易所',
        'F2' => '大连交易所',
        'F3' => '上海期货交易所',
        'F4' => '中国金融期货交易所',
        'F5' => '能源交易所'
    ];

    /**
     * @var string 页面前缀
     */
    protected $view_prefix = "admin.func.contract.jys.";

    /**
     * 首页
     * @param Request $request
     */
    public function index(Request $request){
        $this->log(__CLASS__, __FUNCTION__, $request, "合约-交易所 列表页");
        return view($this->view_prefix.'index');
    }

    /**
     * 数据
     * @param Request $request
     */
    public function pagination(Request $request) {
        $selectInfo = $this->get_params($request, []);
        $condition = $this->getPagingList($selectInfo, []);
        $rows = $request->rows;
        $order = $request->sort ?? 'id';
        $sort = $request->sortOrder ?? 'asc';
        $list = RpaContractJys::where($condition)->orderBy($order, $sort)->paginate($rows);
        return $list;
    }

    /**
     * 新增页
     */
    public function create()
    {
        return parent::create(); // TODO: Change the autogenerated stub
    }

    /**
     * 新增保存
     * @param Request $request
     */
    public function store(Request $request){
        $data = $this->get_params($request, ['name','desc','code']);
        $data['created_by'] = auth()->guard()->user()->id;
        $data['updated_by'] = auth()->guard()->user()->id;
        $result = RpaContractJys::create($data);
        $this->log(__CLASS__, __FUNCTION__, $request, "新增 合约-交易所");
        if($result) {
            return $this->ajax_return(200, '操作成功！');
        } else {
            return $this->ajax_return(500, '保存失败！');
        }
    }

    /**
     * 编辑页
     * @param Request $request
     * @param $id
     */
    public function edit(Request $request, $id){
        $info = RpaContractJys::where('id', $id)->first();
        return view($this->view_prefix.'edit', ['info' => $info]);
    }

    /**
     * 更新数据
     * @param Request $request
     */
    public function update(Request $request){
        $data = $this->get_params($request, ['name','desc','id','code']);
        $data['updated_by'] = auth()->guard()->user()->id;
        $result = RpaContractJys::where('id', $data['id'])->update($data);
        $this->log(__CLASS__, __FUNCTION__, $request, "修改 合约-交易所");
        if($result) {
            return $this->ajax_return(200, '操作成功！');
        } else {
            return $this->ajax_return(500, '保存失败！');
        }
    }

    /**
     * 删除
     * @param Request $request
     * @param $ids
     */
    public function destroy(Request $request, $ids){}

    /**
     * 查询界面
     * @param Request $request
     * @param $id
     */
    public function show(Request $request, $id) {}
}